baseurl = "https://talks.arnaudbos.com/"
languageCode = "en-US"
title = "Arnaud Bos"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Arnaud Bos"
  description = "My corner of teh interweb."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://i-rant.arnaudbos.com/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "https://side-effects.arnaudbos.com/"
[[menu.main]]
  name = "talks"
  identifier = "talks"
  weight = 300
  url = "https://talks.arnaudbos.com/"
[[menu.main]]
  name = "level-up"
  identifier = "level-up"
  weight = 400
  url = "https://level-up.arnaudbos.com/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 500
  url = "https://vitae.arnaudbos.com/"
